# Generated by Django 5.1.3 on 2024-12-02 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post_office", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="postoffice",
            old_name="contactNo",
            new_name="contact_no",
        ),
    ]
