# Generated by Django 5.1.3 on 2024-12-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post_office", "0002_rename_contactno_postoffice_contact_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="postoffice",
            name="rating",
            field=models.CharField(default="0"),
        ),
    ]
