# Generated by Django 5.1.3 on 2024-12-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post_office", "0005_alter_postoffice_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postoffice",
            name="rating",
            field=models.FloatField(default=5.0),
        ),
    ]
