# Generated by Django 5.1.3 on 2024-11-26 18:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("post_office", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("image", models.FileField(upload_to="")),
                ("message", models.CharField(max_length=255)),
                (
                    "action_performed",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("response", models.CharField(blank=True, max_length=255, null=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("createdAt", models.DateTimeField(default=datetime.datetime.now)),
                ("updatedAt", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "escalation_time",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 11, 27, 4, 18, 17, 337661)
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("SUBDIVISIONAL", "Subdivisional"),
                            ("DIVISIONAL", "Divisional"),
                        ],
                        default="SUBDIVISIONAL",
                        max_length=20,
                    ),
                ),
                ("read", models.BooleanField(default=False)),
                (
                    "pincode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="post_office.postoffice",
                    ),
                ),
            ],
        ),
    ]
