# Generated by Django 5.1.3 on 2024-11-26 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="escalation_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 27, 1, 15, 47, 337558)
            ),
        ),
    ]
