# Generated by Django 5.1.3 on 2024-11-26 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_alter_notification_createdat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="escalation_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 11, 26, 19, 59, 16, 697121, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
