# Generated by Django 5.1.3 on 2024-11-26 21:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0006_alter_notification_escalation_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="escalation_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 11, 26, 21, 48, 46, 163144, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
