# Generated by Django 5.1.3 on 2024-11-27 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0008_alter_notification_escalation_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="escalation_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 11, 27, 20, 4, 47, 557146, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
