# Generated by Django 5.1.3 on 2024-12-02 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0012_alter_notification_escalation_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="escalation_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 2, 14, 50, 55, 816728, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
