# Generated by Django 5.1.3 on 2024-12-02 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0014_alter_notification_escalation_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="escalation_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 2, 15, 4, 45, 713905, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
