# Generated by Django 5.1.3 on 2024-12-03 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0016_alter_notification_escalation_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="escalation_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 3, 18, 10, 20, 104586, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
