# Generated by Django 5.1.3 on 2024-12-04 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0017_alter_notification_escalation_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="escalation_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 4, 10, 51, 48, 68356, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
