# Generated by Django 5.1.3 on 2024-12-05 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0018_alter_notification_escalation_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="escalation_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 5, 11, 39, 47, 167523, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
