# Generated by Django 5.1.3 on 2024-12-07 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0019_alter_notification_escalation_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="escalation_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 7, 13, 32, 43, 657242, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
