# Generated by Django 5.1.3 on 2024-12-07 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0020_alter_notification_escalation_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="escalation_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 7, 19, 40, 1, 545125, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
