# Generated by Django 5.1.3 on 2024-12-11 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0022_notification_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="escalation_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 11, 15, 58, 46, 955530, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
