# Generated by Django 5.1.3 on 2024-12-11 18:06

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0023_alter_notification_escalation_time"),
        ("post_office", "0002_rename_contactno_postoffice_contact_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="escalation_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 11, 18, 7, 55, 168252, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.CreateModel(
            name="Complaint",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("createdAt", models.DateTimeField(default=django.utils.timezone.now)),
                ("image", models.FileField(upload_to="")),
                ("description", models.TextField()),
                ("location", models.TextField()),
                ("action", models.BooleanField(default=False)),
                (
                    "pincode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="post_office.postoffice",
                    ),
                ),
            ],
        ),
    ]
