# Generated by Django 5.1.3 on 2024-12-11 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0039_alter_notification_escalation_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="escalation_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 11, 19, 48, 20, 787730, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
