# Generated by Django 5.1.3 on 2024-12-12 03:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0047_alter_notification_escalation_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="escalation_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 12, 3, 40, 29, 932214, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
