# Generated by Django 5.1.3 on 2024-12-12 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0054_alter_notification_escalation_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="escalation_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 12, 11, 27, 32, 936855, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
