# Generated by Django 5.1.3 on 2024-12-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("waste_management", "0003_event_pincode_alter_eventreport_pincode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventreport",
            name="atLocation",
            field=models.CharField(max_length=255),
        ),
    ]
