# Generated by Django 5.1.3 on 2024-12-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("waste_management", "0004_alter_eventreport_atlocation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="attachment",
            field=models.TextField(),
        ),
    ]
