# Generated by Django 5.1.3 on 2024-12-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("waste_management", "0005_alter_event_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventreport",
            name="attached_report",
            field=models.TextField(),
        ),
    ]
