# Generated by Django 5.1.3 on 2024-12-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("waste_management", "0006_alter_eventreport_attached_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="cleaningstaff",
            name="email",
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
